#!/bin/sh

#empty dist directory
rm -rf dist

#create dist directory
mkdir dist

#copy local packages
cp -rf bowl_game bowl_redis bowl_redis_dto cards scoring viewmodels *.py dist

#copy global packages
cp -rf env/lib/python2.7/site-packages/* dist

#go to dist directory and zip everything up
cd dist
file=$(git describe)
zip -r $file.zip .

#remove everything except the zip
find . -type f ! -name $file.zip -delete
find . -type d ! -name $file.zip -delete

#upload to s3
/home/muskiemania/.local/bin/aws --profile webpack-upload-s3 s3 cp *.zip s3://bowl-api

echo $file.zip

#update lambdas:
/home/muskiemania/.local/bin/aws --profile webpack-upload-s3 lambda update-function-code --function-name bowl-create-game-get --s3-bucket bowl-api --s3-key $file.zip
/home/muskiemania/.local/bin/aws --profile webpack-upload-s3 lambda update-function-code --function-name bowl-create-game-post --s3-bucket bowl-api --s3-key $file.zip
/home/muskiemania/.local/bin/aws --profile webpack-upload-s3 lambda update-function-code --function-name bowl-create-player --s3-bucket bowl-api --s3-key $file.zip
/home/muskiemania/.local/bin/aws --profile webpack-upload-s3 lambda update-function-code --function-name bowl-create-deck --s3-bucket bowl-api --s3-key $file.zip
/home/muskiemania/.local/bin/aws --profile webpack-upload-s3 lambda update-function-code --function-name bowl-get-game --s3-bucket bowl-api --s3-key $file.zip
/home/muskiemania/.local/bin/aws --profile webpack-upload-s3 lambda update-function-code --function-name bowl-get-game-auth --s3-bucket bowl-api --s3-key $file.zip
