#!/bin/sh

module=create_game

#empty dist directory
rm -rf dist

#create dist directory
mkdir dist

#copy local packages
cp -rf ../bowl_game dist
cp -rf ../cards dist
cp -rf ../configs dist
cp -rf ../dynamos dist

cp ../lambdas/create_game.py dist

#copy global packages
#cp -rf env/lib/python2.7/site-packages/* dist

#go to dist directory and zip everything up
cd dist
file=$module_$(git describe)
zip -r $file.zip .

#remove everything except the zip
find . -type f ! -name $file.zip -delete
find . -type d ! -name $file.zip -delete

cp $file.zip $module.zip

#upload to s3
aws --profile s3-user s3 cp $file.zip s3://bowlme-cicd/artifacts/$file.zip
aws --profile s3-user s3 cp $module.zip s3://bowlme-cicd/v2/$module.zip

#echo $file.zip

#update lambdas:
#/home/muskiemania/.local/bin/aws --profile webpack-upload-s3 lambda update-function-code --function-name bowl-create-game-get --s3-bucket bowl-api --s3-key $file.zip
#/home/muskiemania/.local/bin/aws --profile webpack-upload-s3 lambda update-function-code --function-name bowl-create-game-post --s3-bucket bowl-api --s3-key $file.zip
#/home/muskiemania/.local/bin/aws --profile webpack-upload-s3 lambda update-function-code --function-name bowl-create-player --s3-bucket bowl-api --s3-key $file.zip
#/home/muskiemania/.local/bin/aws --profile webpack-upload-s3 lambda update-function-code --function-name bowl-create-deck --s3-bucket bowl-api --s3-key $file.zip
#/home/muskiemania/.local/bin/aws --profile webpack-upload-s3 lambda update-function-code --function-name bowl-get-game --s3-bucket bowl-api --s3-key $file.zip
#/home/muskiemania/.local/bin/aws --profile webpack-upload-s3 lambda update-function-code --function-name bowl-get-game-auth --s3-bucket bowl-api --s3-key $file.zip
